
on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: npm install

      # - name: Build project
      #   run: npx ng build # or your specific build command

      - id: build-publish
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          path: dist/talkback/browser # default
          build_command: npm run build -- --base-href=/${{ github.event.repository.name }}/ # default
